services:
  pelican:
    build: .
    container_name: fabrica-prod-door
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - fabrica-door-network

networks:
  fabrica-door-network:
    driver: bridge
