name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # # Login no Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # # Build e push da imagem Docker
      # - name: Build and push Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Configurar SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Deploy no VPS via SSH
      - name: Deploy to VPS
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
           whoami
          EOF

      # Opcional: Configuração VPN (descomente se necessário)
      - name: Setup VPN
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn.conf
          sudo openvpn --config vpn.conf --auth-user-pass <(echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}") &
          sleep 5 # Aguarda conexão VPN estabelecer
