name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do repositório
      - uses: actions/checkout@v3

      # 2. Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Constrói e publica a imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t fabrica-door:latest .
          docker tag fabrica-door:latest fabricioifc/fabrica-door:${{ github.sha }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push fabricioifc/fabrica-door:${{ github.sha }}

      # 4. Instala cliente VPN (exemplo: OpenVPN)
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      # 5. Conecta à VPN
      - name: Connect to VPN
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          VPN_CONFIG: ${{ secrets.VPN_CONFIG }} # Conteúdo do arquivo .ovpn
        run: |
          echo "$VPN_CONFIG" > vpn-config.ovpn  # Arquivo de configuração da VPN
          echo "$VPN_USERNAME" > auth.txt
          echo "$VPN_PASSWORD" >> auth.txt
          sudo openvpn --config vpn-config.ovpn --auth-user-pass auth.txt --daemon --log /tmp/vpn.log
          sleep 10  # Aguarda a conexão estabilizar

      # New Step: Check VPN Logs if Connection Fails
      - name: Check VPN Logs
        if: failure()
        run: cat /tmp/vpn.log

      # 6. Implanta no servidor via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Recomendado: chave SSH
          # password: ${{ secrets.SSH_PASSWORD }}  # Alternativa: senha SSH (menos segura)
          port: ${{ secrets.SSH_PORT }} # Ex.: 2222
          script: |
            docker pull fabricioifc/fabrica-door:${{ github.sha }}
            cd /home/${{ secrets.SSH_USER }}/fabrica-door
            docker-compose up -d --force-recreate
