name: Deploy with Docker Hub and SSH

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Build e push da imagem para o Docker Hub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fabrica-door:latest

      # 2. Conexão via OpenVPN
      # - name: Setup OpenVPN
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y openvpn

      # - name: Configure OpenVPN
      #   run: |
      #     echo "${{ secrets.OPENVPN_CONFIG }}" > config.ovpn
      #     echo -e "${{ secrets.OPENVPN_USERNAME }}\n${{ secrets.OPENVPN_PASSWORD }}" > auth.txt
      #     sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon
      #     sleep 10

      # # 3. Deploy via SSH
      # - name: Add SSH private key
      #   uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute deploy commands
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/fabrica-door:latest
            cd /opt/fabrica-door-docker
            docker-compose down
            docker-compose up -d
          "
