name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # # Login no Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # # Build e push da imagem Docker
      # - name: Build and push Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Opcional: Configuração VPN (descomente se necessário)
      - name: Setup VPN
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn.conf
          sudo openvpn --config vpn.conf --auth-user-pass <(echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}") &
          sleep 5 # Aguarda conexão VPN estabelecer

      # Configuração SSH com debug
      - name: Setup SSH with Debug
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "SSH Key contents (sanitized):"
          head -n 2 ~/.ssh/id_rsa
          echo "Trying to scan host ${{ secrets.SSH_HOST }} on port ${{ secrets.SSH_PORT }}"
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -v ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 2>&1 || echo "Keyscan failed"
          echo "Known hosts contents:"
          cat ~/.ssh/known_hosts
          echo "Testing SSH connection..."
          ssh -v -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo SSH test successful" || echo "SSH connection failed"

      # Deploy no VPS via SSH
      - name: Deploy to VPS
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
           whoami
          EOF
