name: Deploy to Home Directory

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build e push da imagem
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fabrica-door:latest

      # Deploy via SSH
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Remote Commands
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.SSH_PORT }} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            # Criar diretório se necessário
            mkdir -p /home/${{ secrets.SSH_USER }}/fabrica-door
            
            # Atualizar containers
            docker pull ${{ secrets.DOCKER_USERNAME }}/fabrica-door:latest
            cd /home/${{ secrets.SSH_USER }}/fabrica-door
            docker-compose down
            docker-compose up -d
          "
