name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do repositório
      - uses: actions/checkout@v3

      # 2. Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Constrói e publica a imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t fabrica-door:latest .
          docker tag fabrica-door:latest fabricioifc/fabrica-door:${{ github.sha }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push fabricioifc/fabrica-door:${{ github.sha }}

      # 4. Instala cliente VPN (exemplo: OpenVPN)
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      # 5. Conecta à VPN
      - name: Connect to VPN
        run: |
          # Instala o OpenVPN
          sudo apt-get update
          sudo apt-get install -y openvpn

          # Escreve o arquivo de configuração da VPN
          echo "$VPN_CONFIG" > vpn-config.ovpn

          # Escreve as credenciais no arquivo auth.txt
          echo "$VPN_USERNAME" > auth.txt
          echo "$VPN_PASSWORD" >> auth.txt

          # Verifica os arquivos
          if [ ! -s vpn-config.ovpn ] || [ ! -s auth.txt ]; then
            echo "Erro: Arquivos de configuração ou autenticação estão vazios!"
            exit 1
          fi

          # Mostra o conteúdo dos arquivos para debug (opcional, remova se sensível)
          echo "Conteúdo de vpn-config.ovpn (primeiras 5 linhas):"
          head -n 5 vpn-config.ovpn
          echo "Conteúdo de auth.txt:"
          cat auth.txt

          # Tenta conectar à VPN sem daemon para capturar erros diretamente
          echo "Tentando conectar à VPN..."
          openvpn --config vpn-config.ovpn --auth-user-pass auth.txt --verbose > vpn.log 2>&1

          # Verifica se houve erro na execução
          if [ $? -ne 0 ]; then
            echo "Erro: O comando openvpn falhou. Aqui estão os logs:"
            cat vpn.log || echo "Erro: Nenhum log gerado!"
            exit 1
          fi

          # Se chegou aqui, verifica se a conexão foi bem-sucedida
          if grep -q "Initialization Sequence Completed" vpn.log; then
            echo "VPN conectada com sucesso!"
          else
            echo "Erro: VPN não conectou. Aqui estão os logs:"
            cat vpn.log
            exit 1
          fi
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          VPN_CONFIG: ${{ secrets.VPN_CONFIG }}

      # 6. Implanta no servidor via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Recomendado: chave SSH
          # password: ${{ secrets.SSH_PASSWORD }}  # Alternativa: senha SSH (menos segura)
          port: ${{ secrets.SSH_PORT }} # Ex.: 2222
          script: |
            docker pull fabricioifc/fabrica-door:${{ github.sha }}
            cd /home/${{ secrets.SSH_USER }}/fabrica-door
            docker-compose up -d --force-recreate
